### ISSUE TITLE
click detected outside button

### ISSUE THREAD

**Issue by maujabur** [openrndr/openrndr-panel#2] opened 2019-07-21 02:21 UTC
When using the examples ui-001 and ui-002 from the OPENRNDR tutorials, the clicks are detected even when clicking outside the button

**Comment by edwinRNDR** [comment] 2019-12-05 09:34
It looks like this is fixed as a side-effect of recent changes to Panel. I couldn't reproduce this at least.

**Comment by ricardomatias** [comment] 2020-01-08 14:24
This was fixed with my commit 361df98. But the fix should be removed and another solution taken. @edwinRNDR we need to differentiate between Panel mouse events and the rest. Perhaps add a bounding box to the drawn panel and figure out there if it's for the Panel or outside.

**Comment by sbauer322** [comment] 2020-02-03 03:21
For what it's worth, I'd second the more elaborate solution that needs to differentiate between Panel mouse events and the rest.

I'm encountering a similar problem, with panel 0.3.19 and 0.3.20. I have a mouse drag event that ideally only fires for the canvas (for lack of a better word) but ends up being triggered when using a slider as well. 

In the clip below the drag event gets picked up when using the slider, which draws extra lines along the edge of the shape.

![openrndr-slider-drag-event](https://user-images.githubusercontent.com/2945386/73623240-46395080-460a-11ea-927e-6515b82c80a1.gif)

**Comment by edwinRNDR** [comment] 2020-02-03 14:53
@sbauer322 the Slider control marks the drag event as already handled by setting `propagationCancelled` to `true`. 

In your program you can check that as follows.

```
program {
    mouse.dragged.listen {
        if (!it.propagationCancelled) {
            // -- handle the event
        }
    }
}
```

- [ ] Update OPENRNDR guide with instructions for using `propagationCancelled`

**Comment by sbauer322** [comment] 2020-02-03 15:09
Oh, awesome - thanks for mentioning this!

EDIT: Just to point out in case anyone in the future runs into this - the slider needs to come before the dragged event in the code in order for the slider to consume the event first. This is mentioned in the guide.

**Comment by edwinRNDR** [comment] 2020-03-11 11:11
https://github.com/openrndr/openrndr-panel/commit/3c26a9cd3908514901b5a7d45aae8123edd254e6 prevents the Body from consuming the mouse click event

**Closed as completed by edwinRNDR** 2020-03-11 11:11 UTC
